name: Update CHANGELOG

on:
  pull_request:
    types: [closed]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Update CHANGELOG
        if: contains(github.event.pull_request.labels.*.name, 'gh-workflow-bot')
        run: |
          echo "## $(date +%Y-%m-%d)" >> CHANGELOG.md
          echo "- $(github.event.pull_request.title)" >> CHANGELOG.md

      - name: Create commit
        if: contains(github.event.pull_request.labels.*.name, 'gh-workflow-bot')
        run: git commit -am "Update changelog"

      - name: Create pull request
        if: contains(github.event.pull_request.labels.*.name, 'gh-workflow-bot')
        uses: peter-evans/create-pull-request@v4
        with:
          title: "Update CHANGELOG"
          body: |
            This pull request updates the CHANGELOG.md file with the changes from the recently merged pull request.
          branch: changelog-update-$(date +'%Y-%m-%d-%H-%M-%S')
          labels: gh-workflow-bot
